use lib '.';
use strict;
use warnings;

use inc::Module::Install;

# Definition.
abstract 'Tags helpers for HTML elements.';
author 'Michal Josef Spacek <skim@cpan.org>';
author_requires 'English' => 0;
author_requires 'File::Object' => 0;
author_requires 'Test::More' => 0;
author_requires 'Test::NoWarnings' => 0;
author_requires 'Test::Pod' => 0;
author_requires 'Test::Pod::Coverage' => 0;
license 'bsd';
name 'Tags-HTML-Element-Form-Items';
perl_version 5.008;
readme_from 'Items.pm';
recursive_author_tests('xt');
requires 'Data::HTML::Element::Form' => 0;
requires 'Tags::HTML' => 0.04;
requires 'Tags::HTML::Element::Form' => 0;
requires 'Tags::HTML::Element::Item' => 0;
resources 'bugtracker' => 'https://github.com/michal-josef-spacek/Tags-HTML-Element-Form-Items/issues';
resources 'homepage' => 'https://github.com/michal-josef-spacek/Tags-HTML-Element-Form-Items';
resources 'repository' => 'git://github.com/michal-josef-spacek/Tags-HTML-Element-Form-Items';
test_requires 'Test::More' => 0;
test_requires 'Test::NoWarnings' => 0;
tests_recursive;
version '0.01';

# Run.
WriteAll();
